mutation createRecipe(
  $title: String!
  $description: String
  $ingredients: [String!]!
) {
  addRecipe(
    newRecipeData: {
      title: $title
      description: $description
      ingredients: $ingredients
    }
  ) {
    id
    title
    description
    ingredients
  }
}

mutation updateRecipe(
  $id: String!
  $title: String!
  $description: String
  $ingredients: [String!]!
) {
  updateRecipe(
    id: $id
    updateRecipeData: {
      title: $title
      description: $description
      ingredients: $ingredients
    }
  ) {
    id
    title
    description
    ingredients
  }
}

mutation removeRecipe($id: String!) {
}
